# Generated by Django 3.0.5 on 2020-07-23 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mlproject',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('slug', models.CharField(default='test', max_length=100)),
                ('code', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 23, 11, 25, 35, 932948))),
            ],
        ),
        migrations.CreateModel(
            name='pythonproject',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('slug', models.CharField(default='test', max_length=100)),
                ('code', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 23, 11, 25, 35, 931947))),
            ],
        ),
        migrations.CreateModel(
            name='webdevproject',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('slug', models.CharField(default='test', max_length=100)),
                ('code', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 23, 11, 25, 35, 932448))),
            ],
        ),
    ]
